version: "3.8"

services:
  ais0622:
    container_name: ais0622
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    cpuset: "0-2"
    ports:
      - 8525:8100
      - 5525:5525/udp
      - 4025:4025/udp
      - 5258:5258/tcp
      - 5631:5631/tcp
    volumes:
      - ./stats:/data:rw
      - ./plugins:/home/plugins/:ro
    command: >
             -N 8100 SERVER_MODE on FILE /data/stats.bin BACKUP 5 ABOUT /data/about.md LAT ${ST_LAT} LON ${ST_LON} STATION ${ST_NAME} STATION_LINK ${ST_LINK} PLUGIN_DIR /home/plugins PROME on MESSAGE on                  
             -x 0.0.0.0 5525 -o 1 -q -v 10
             -x 0.0.0.0 4025 -o 1 -q -v 10
             -t data.aishub.net 5258 -gt FORMAT txt PROTOCOL none PERSIST on RESET 60 -o 1 -q -v 10
             -t 153.44.253.27 5631 -gt FORMAT txt PROTOCOL none PERSIST on RESET 60 -o 1 -q -v 10
 #           -D postgresql://admin:nuc6i5HQ[k@100.110.69.122/ais  STATION_ID 4541 NMEA off BS on MSGS off
             
networks:
  default:
    name: aisring
    external: true